### ISSUE TITLE
Exposed .git/config

### ISSUE THREAD

**Issue by userbradley** [d-Rickyy-b/d-rickyy-b.github.io#2]
hello,

I am bradley from breadnet.co.uk
Firstly, thanks for linking to my site! Greatly appreciated!

I have had a look at your site and have seen that there is an exposed .git/config file

You can see it here: rico-j.de/.git/config

```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://d-Rickyy-b:f39baa312933da5c6b1845047d8fc34f0a10bd90@github.com/d-Rickyy-b/rico-j.de.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
	remote = origin
	merge = refs/heads/master
```

You may want to remove this, but it's not really the end of the world. Just thought I should make you aware!

Thanks,

Bradley
breadNET

**Comment by d-Rickyy-b** [comment]
Hi Bradley, damn, I fixed that half a year ago. Now I recently switched to nginx and forgot to apply a fix when writing the new config. Thank you very much for creating an issue :) - much appreciated.

I added a fix just now:
```
location ~ /\.git {
 deny all;
}
```
